import Sidebar from "../components/Sidebar";
import type { Metadata } from "next";
import { Saira } from "next/font/google";
import "./globals.css";

const saira = Saira({
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full antialiased">
      <body className={`${saira.className} min-h-screen`}>

        <div className="flex flex-col md:flex-row">
          <Sidebar />

          <main className="w-full flex-1 min-w-0">
            {children}
          </main>
        </div>

      </body>
    </html>
  );
}
